# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: introspective
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    #substitute production appsettings entries to appsettings json file
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{env.DOTNET_ROOT}}/introspective/appsettings.json'
      env:
        AzureAdB2C.Instance: ${{ secrets.INSTANCE }}
        AzureAdB2C.ClientId: ${{ secrets.CLIENTID }}
        AzureAdB2C.Domain: ${{ secrets.DOMAIN }}
        AzureAdB2C.secretValue: ${{ secrets.SECRETVALUE }}
        AzureAdB2C.secretId: ${{ secrets.SECRETID }}
      
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/introspective
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - uses: azure/webapps-deploy@v3
      name: Deploy
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/introspective'
